name: Deploy Amoeba Post

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  post-to-x:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
      X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Amoeba bot
      run: |
        python src/amoeba/core.py
