name: Amoeba Scheduled Tweet

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
      X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      AMOEBA_PERSONAS: ${{ secrets.AMOEBA_PERSONAS }}
      AMOEBA_PERSONA: ${{ secrets.AMOEBA_PERSONA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Amoeba Bot
        run: |
          python src/amoeba/bot.py --now
